name: volo
description: "Volo app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  dropdown_search: ^5.0.6
  flutter_typeahead: ^5.2.0
  pointer_interceptor: ^0.10.1+2
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_app_check: ^0.3.2+9
  firebase_ai: ^2.2.1
  firebase_remote_config: ^5.0.0
  flutter_contacts: ^1.1.7+1
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  google_generative_ai: ^0.4.7
  lottie: ^3.3.1
  provider: ^6.1.2
  confetti: ^0.7.0
  flutter_local_notifications: ^17.2.2
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/onboarding_illustration3.png
    - assets/test.png
    - assets/volo_app_icon.png
    - assets/animations/file_searching.json
    - assets/airports_global.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#00000000"
  remove_alpha_ios: true
